export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  category: string;
}

const QUESTIONS: QuizQuestion[] = [
  // ═══════════════════════════════════════════════════════════════
  // SVT — 室上性心动过速（40 题）
  // ═══════════════════════════════════════════════════════════════

  // AVNRT 基础
  { id: "s01", question: "关于 AVNRT（房室结折返性心动过速），以下哪项描述是正确的？", options: ["通常由房室旁路引起", "折返环位于房室结区域，慢-快型最常见", "心电图可见明显的 delta 波", "首选治疗是腺苷静脉推注，其他方法均无效"], correct: 1, explanation: "AVNRT 折返环位于房室结区域，慢-快型（slow-fast）占 80-90%。慢径前传、快径逆传。delta 波是预激综合征的特征。", category: "SVT" },
  { id: "s02", question: "典型 AVNRT（慢-快型）的折返路径是哪一种？", options: ["快径前传，慢径逆传", "慢径前传，快径逆传", "旁路前传，房室结逆传", "房室结前传，旁路逆传"], correct: 1, explanation: "典型 AVNRT（慢-快型）：慢径前传（AH 延长）→ 快径逆传（VA 短）。非典型 AVNRT（快-慢型）：快径前传 → 慢径逆传（VA > AH）。", category: "SVT" },
  { id: "s03", question: "在典型 AVNRT 中，最早的逆行心房激动通常记录于哪个部位？", options: ["冠状窦近端（CS 9-10）", "His 束区域", "右房侧壁", "左房后壁"], correct: 1, explanation: "典型 AVNRT 逆传经过快径，最早逆行心房激动在 His 束区域（前间隔）。冠状窦口附近最早激动提示非典型 AVNRT 或房速。", category: "SVT" },
  { id: "s04", question: "关于慢径消融治疗 AVNRT，以下哪项描述是正确的？", options: ["靶点位于 Koch 三角的尖部（His 束附近）", "靶点位于冠状窦口与三尖瓣环之间（Koch 三角基底部）", "必须在心动过速发作时消融", "消融终点是消除所有交界性心律"], correct: 1, explanation: "慢径消融靶点在冠状窦口与三尖瓣环之间的峡部区域（Koch 三角基底部）。解剖消融法或电位引导法均可。术中交界心律是敏感但非特异的终点指标。", category: "SVT" },
  { id: "s05", question: "慢径消融过程中出现快速交界心律（>150 bpm）应如何处理？", options: ["这是正常现象，继续放电", "立即停止放电，评估房室传导", "加大功率加速消融", "给予腺苷后继续消融"], correct: 1, explanation: "快速交界心律（>150 bpm）或出现 VA 阻滞提示房室传导受损风险，应立即停止放电。慢径消融的安全监测包括 PR 间期和 VA 传导。", category: "SVT" },

  // AVRT / WPW
  { id: "s06", question: "顺向型 AVRT（orthodromic AVRT）的传导路径是？", options: ["旁路前传，房室结逆传", "房室结前传，旁路逆传", "仅通过旁路传导", "仅通过房室结传导"], correct: 1, explanation: "顺向型 AVRT（95%）：房室结前传 → 心室 → 旁路逆传 → 心房。QRS 窄（除非合并差传）。逆向型 AVRT（5%）：旁路前传 → 心室 → 房室结逆传，QRS 宽。", category: "SVT" },
  { id: "s07", question: "心电图 delta 波的特征是？", options: ["QRS 波终末部增宽", "PR 间期延长", "QRS 波起始部粗钝、PR 间期缩短", "QT 间期延长"], correct: 2, explanation: "Delta 波是旁路前向传导提前激动心室的表现：PR 间期缩短（<120ms）+ QRS 起始部粗钝（delta 波）+ QRS 增宽。旁路位置不同，delta 波极性不同。", category: "SVT" },
  { id: "s08", question: "关于 WPW 综合征合并房颤，以下哪项处理是禁忌的？", options: ["同步直流电复律", "伊布利特静脉应用", "静脉推注腺苷/维拉帕米", "普鲁卡因胺静脉应用"], correct: 2, explanation: "WPW 合并房颤时，阻断房室结的药物（腺苷、维拉帕米、地高辛、β 受体阻滞剂）可促使更多激动经旁路下传，诱发室颤。应使用阻断旁路的药物（伊布利特、普鲁卡因胺）或直接电复律。", category: "SVT" },
  { id: "s09", question: "以下哪项不是预激综合征高危特征的指标？", options: ["房颤时最短预激 RR 间期 < 250ms", "多旁路", "旁路不应期 < 270ms（心房递增起搏时）", "PR 间期 > 120ms"], correct: 3, explanation: "PR 间期缩短（<120ms）是预激特征，不是危险分层指标。高危指标：房颤时最短预激 RR < 250ms、旁路不应期 < 270ms、多旁路、Ebstein 畸形合并旁路。", category: "SVT" },
  { id: "s10", question: "左侧游离壁旁路在心电图上的典型表现为？", options: ["V1 导联 delta 波正向，I、aVL 导联 delta 波负向", "V1 导联 delta 波负向，II、III、aVF 导联 delta 波负向", "胸前导联移行在 V1-V2", "I、aVL 导联 delta 波负向，V1 导联 delta 波正向"], correct: 0, explanation: "左侧旁路：V1 导联 delta 波正向（类 RBBB 形态），I 和 aVL 导联 delta 波负向。右侧旁路：V1 导联 delta 波负向。后间隔旁路：II、III、aVF 导联 delta 波负向。", category: "SVT" },

  // 房性心动过速
  { id: "s11", question: "关于房性心动过速（AT），以下哪项描述是正确的？", options: ["折返环依赖房室结", "心房率通常为 150-250 bpm，P 波形态与窦性不同", "腺苷可终止所有房速", "AT 的 P 波形态与窦性 P 波完全相同"], correct: 1, explanation: "AT 起源于心房肌，不依赖房室结或旁路。腺苷可终止触发活动或 cAMP 介导的 AT，但对微折返性 AT 无效（仅产生一过性房室阻滞）。P 波形态取决于起源部位。", category: "SVT" },
  { id: "s12", question: "关于多源性房性心动过速（MAT），以下哪项是其典型特征？", options: ["常见于健康年轻人", "P 波至少有 3 种形态，PP 和 PR 间期多变", "电复律是首选治疗", "心房率 > 350 bpm"], correct: 1, explanation: "MAT 诊断标准：≥3 种不同形态 P 波 + 心房率 100-250 bpm + PP/PR/RR 间期多变。最常见于 COPD 急性加重期。治疗以处理基础疾病为主（纠正缺氧、电解质紊乱），维拉帕米可能有效。", category: "SVT" },
  { id: "s13", question: "自律性房性心动过速对腺苷的反应是？", options: ["终止心动过速", "产生一过性房室阻滞，暴露持续的心房活动", "加速心室率", "完全无效，心率无变化"], correct: 1, explanation: "自律性 AT 不被腺苷终止（不依赖触发活动），但腺苷可产生一过性房室阻滞，暴露持续的心房激动，帮助诊断。微折返性 AT 同理。", category: "SVT" },
  { id: "s14", question: "界嵴（crista terminalis）房速的 P 波特征通常是？", options: ["V1 导联 P 波负向", "I 和 aVL 导联 P 波正向", "下壁导联 P 波正向，V1 导联 P 波双向或正向", "所有导联 P 波负向"], correct: 2, explanation: "界嵴是右房最常见的 AT 起源部位（沿界嵴从上到下分布）。上界嵴起源：下壁导联 P 波正向；下界嵴起源：下壁导联 P 波负向。V1 导联 P 波通常双向或正向。", category: "SVT" },

  // 鉴别诊断
  { id: "s15", question: "短 RP 心动过速的鉴别诊断不包括以下哪项？", options: ["典型 AVNRT（慢-快型）", "顺向型 AVRT（快旁路逆传）", "非典型 AVNRT（快-慢型）", "房速伴 PR 延长"], correct: 2, explanation: "短 RP 心动过速（RP < PR）：① 典型 AVNRT（慢-快型）② 顺向型 AVRT ③ AT 伴 PR 延长。非典型 AVNRT（快-慢型）和 PJRT 表现为长 RP 心动过速（RP > PR）。", category: "SVT" },
  { id: "s16", question: "以下哪项对鉴别 AVNRT 与顺向型 AVRT 最有帮助？", options: ["心率", "QRS 波宽度", "心动过速时出现功能性 LBBB 伴 VA 间期延长", "ST 段压低程度"], correct: 2, explanation: "Coumel 定律：心动过速中出现功能性 BBB 时，如果 VA 间期延长 > 20ms，则旁路位于阻滞侧游离壁（同侧旁路）。AVNRT 不依赖心室，BBB 不影响 VA 间期。", category: "SVT" },
  { id: "s17", question: "以下哪项心电图特征最支持 AT 而非 AVNRT 的诊断？", options: ["窄 QRS 波", "心率 180 bpm", "心率自发增快和减慢（warm-up / cool-down）", "Valsalva 动作可终止心动过速"], correct: 2, explanation: "自律性 AT 典型特征为 warm-up（心率逐渐增快）和 cool-down（逐渐减慢）。AVNRT 和 AVRT 通常突发突止。迷走神经刺激可终止 AVNRT/AVRT，对自律性 AT 无效。", category: "SVT" },
  { id: "s18", question: "心内电生理检查中，心室起搏时出现偏心性心房激动顺序提示什么？", options: ["AVNRT", "旁路逆传", "房室结双径路", "交界性心动过速"], correct: 1, explanation: "心室起搏或心动过速时，心房激动顺序呈偏心性（最早激动不在 His 束区域而在冠状窦或右房侧壁）强烈提示旁路逆传。AVNRT 的逆传心房激动呈向心性（最早在 His 束区域）。", category: "SVT" },

  // 交界性心动过速
  { id: "s19", question: "关于交界性心动过速（JT），以下哪项正确？", options: ["P 波在 QRS 之前", "房室分离是其特征", "腺苷可终止大多数 JT", "JT 仅见于儿童"], correct: 1, explanation: "JT 发作时常表现为房室分离（心房和心室各自独立激动）。PJRT（持续性交界性反复性心动过速）是特殊类型，表现为长 RP 心动过速，由慢旁路逆传引起。", category: "SVT" },
  { id: "s20", question: "PJRT（持续性交界性反复性心动过速）的旁路位于最常见哪个部位？", options: ["左侧游离壁", "前间隔（His 束旁）", "后间隔（冠状窦口附近）", "右室游离壁"], correct: 2, explanation: "PJRT 的旁路最常见于后间隔区域（冠状窦口附近），为具有递减传导特性的慢旁路（只逆传），靶点通常在后间隔三尖瓣环区域。", category: "SVT" },

  // 更多 SVT 进阶题
  { id: "s21", question: "关于 Mahaim 纤维，以下哪项描述是正确的？", options: ["它是房室结的异常分支", "只具备逆传功能", "具备前向递减传导功能，无逆传功能", "最常见于左心室游离壁"], correct: 2, explanation: "Mahaim 纤维（房束旁路/束室旁路）：位于右侧，只有前向递减传导（腺苷敏感），无逆传功能。心动过速呈 LBBB 形态，靶点在三尖瓣环记录到 Mahaim 电位处。", category: "SVT" },
  { id: "s22", question: "关于阵发性 SVT 急性终止，以下哪项处理策略是错误的？", options: ["血流动力学稳定者首选迷走神经刺激", "腺苷 6mg → 12mg → 18mg 快速静脉推注", "血流动力学不稳定者直接同步电复律", "所有窄 QRS 心动过速都首选维拉帕米"], correct: 3, explanation: "虽然维拉帕米对 AVNRT/AVRT 有效，但未明确诊断前不应首选——AT 对维拉帕米反应不一，且如患者有潜在心功能不全可能诱发心衰。腺苷因其超短半衰期更安全，可同时用于诊断和治疗。", category: "SVT" },
  { id: "s23", question: "以下哪种情况出现房室分离时最支持 VT 的诊断？", options: ["心动过速频率 150 bpm", "QRS 宽度 110ms", "存在融合波（fusion beat）和夺获波（capture beat）", "电轴正常"], correct: 2, explanation: "融合波和夺获波是 VT 的特异性指标——在房室分离时，窦性激动偶尔下传夺获心室（capture beat）或与室性激动融合（fusion beat）。宽 QRS 心动过速中出现这些征象强烈支持 VT。", category: "SVT" },
  { id: "s24", question: "关于隐匿性旁路，以下哪项正确？", options: ["心电图有 delta 波", "旁路只能前传，不能逆传", "旁路只能逆传，不能前传（窦律时心电图正常）", "腺苷可揭示 delta 波"], correct: 2, explanation: "隐匿性旁路：只能逆传（心室→心房），窦律心电图正常（无 delta 波）。但可参与顺向型 AVRT。约占旁路的 30-40%。显性旁路（WPW 型）可双向传导或仅前传。", category: "SVT" },
  { id: "s25", question: "以下哪项是 Ebstein 畸形最常合并的心律失常？", options: ["心房颤动", "右侧旁路/WPW 综合征", "房室传导阻滞", "窦房结功能障碍"], correct: 1, explanation: "Ebstein 畸形（三尖瓣下移畸形）约 20-30% 合并右侧旁路，且常为多旁路。右房扩大也增加房速和房扑风险。旁路消融在 Ebstein 畸形中难度增加（三尖瓣环解剖变异）。", category: "SVT" },
  { id: "s26", question: "关于慢径消融改良术的并发症，以下哪项最重要需警惕？", options: ["心包积液", "完全性房室传导阻滞（需永久起搏器）", "冠状动脉损伤", "肺栓塞"], correct: 1, explanation: "慢径消融最严重的并发症是完全性房室传导阻滞（发生率 < 1%）。损伤快径或 His 束可导致。预防措施：解剖消融远离 His 束区域，监测交界心律和 VA 传导，出现快速交界心律或 VA 阻滞立即停止。", category: "SVT" },
  { id: "s27", question: "以下哪种心动过速，腺苷推注后可能出现\"腺苷敏感性\"—心动过速终止后立即再发？", options: ["典型 AVNRT", "顺向型 AVRT", "窦房结折返性心动过速", "自律性房速"], correct: 2, explanation: "腺苷终止心动过速后，窦房结折返性心动过速常因腺苷诱发窦性停搏后的代偿性窦速而再发。AT 也可能因腺苷后房早诱发而再发。", category: "SVT" },
  { id: "s28", question: "顺向型 AVRT 合并左束支阻滞（功能性）时，如果 VA 间期比无阻滞时延长 35ms，旁路位于？", options: ["右侧游离壁", "左侧游离壁", "前间隔", "后间隔"], correct: 1, explanation: "Coumel 定律的具体应用：功能性左束支阻滞导致 VA 间期延长 > 20ms，说明旁路在左侧（同侧旁路）——激动必须从右室经室间隔传到左室后才能经旁路逆传，路径延长。", category: "SVT" },
  { id: "s29", question: "在电生理检查中使用心室起搏诊断隐匿性旁路的常用方法是？", options: ["心房程序刺激", "心室程序刺激，观察逆传心房激动顺序", "腺苷试验", "异丙肾诱发"], correct: 1, explanation: "心室程序刺激（S1S2 递减）观察逆传心房激动顺序：向心性激动（最早 His 束区域）提示房室结逆传；偏心性激动提示旁路逆传。心室 RS2 刺激也可揭示旁路。", category: "SVT" },
  { id: "s30", question: "关于 1:1 房室传导的 SVT 伴宽 QRS 波，以下哪项不支持 SVT 合并差传的诊断？", options: ["QRS 呈典型 RBBB 或 LBBB 形态", "心动过速起始于房早", "出现房室分离", "Valsalva 动作可终止心动过速"], correct: 2, explanation: "房室分离是 VT 的标志，不支持 SVT 合并差传。SVT 合并差传的特点：典型 BBB 形态、起始于房早、可被迷走刺激终止、QRS 初始向量与窦律一致。", category: "SVT" },
  { id: "s31", question: "关于房室结双径路现象，以下哪项电生理表现符合诊断标准？", options: ["心房 S1S2 递减 10ms 时，AH 间期跳跃 ≥ 50ms", "HV 间期 > 55ms", "心房起搏 1:1 传导的最短周期 < 300ms", "心室起搏 VA 递减传导"], correct: 0, explanation: "房室结双径路诊断标准：心房程序刺激 S1S2 递减 10ms 时，AH 间期跳跃 ≥ 50ms（快径不应，激动从慢径下传）。有时可见\"双重心室反应\"（1 个房早起搏产生 2 个 QRS）。", category: "SVT" },
  { id: "s32", question: "关于房室结折返的\"诱发窗口\"，以下哪项正确？", options: ["只需心房早搏刺激即可诱发", "需要快径和慢径的不应期差形成传导阻滞和折返条件", "心室刺激不能诱发 AVNRT", "异丙肾无法扩大诱发窗口"], correct: 1, explanation: "AVNRT 诱因：房早在快径被阻滞，激动沿慢径下传 → 快径脱离不应期后逆传形成折返。快径不应期 > 慢径不应期是必要条件。异丙肾可改变不应期匹配，促进诱发。", category: "SVT" },
  { id: "s33", question: "关于 AMC 旁路（anteroseptal / 前间隔旁路）的消融风险，以下哪项最高？", options: ["冠脉损伤", "完全性房室传导阻滞", "心包积液", "膈神经损伤"], correct: 1, explanation: "前间隔旁路和中间隔旁路紧邻 His 束和房室结，消融导致完全性房室传导阻滞的风险最高。应使用低能量起始、密切监测 His 电位、考虑冷冻消融（cryoablation）以提高安全性。", category: "SVT" },
  { id: "s34", question: "哪一类抗心律失常药物通过阻断 IKr 钾通道延长不应期，对旁路和房室结构均有作用？", options: ["氟卡尼（I C 类）", "维拉帕米（IV 类）", "伊布利特（III 类）", "利多卡因（I B 类）"], correct: 2, explanation: "伊布利特（III 类）阻断 IKr 钾通道，延长心房和心室不应期，对旁路和房室结均有效。可用于 WPW 合并房颤（阻断旁路传导）。氟卡尼也阻断旁路（I C 类），但结构性心脏病禁用。", category: "SVT" },
  { id: "s35", question: "在典型的慢-快 AVNRT 中，以下哪个间期描述正确？", options: ["AH > HA", "HA > AH", "AH = HA", "AH 和 HA 无法测量"], correct: 0, explanation: "典型 AVNRT（慢-快型）：AH 间期长（慢径前传）→ HA 间期短（快径逆传），AH > HA。非典型（快-慢型）：AH 短 → HA 长，AH < HA。", category: "SVT" },
  { id: "s36", question: "以下哪项是终止 AVNRT 最有效的迷走神经刺激方法？", options: ["颈动脉窦按摩", "改良 Valsalva 动作（吹气后抬高双腿）", "眼球压迫", "面部冷水浸泡"], correct: 1, explanation: "REVERT 试验（2015，Lancet）证实改良 Valsalva 动作（标准 Valsalva 后立即抬高双腿至 45°）转复率 43%，显著优于标准 Valsalva 的 17%。颈动脉窦按摩和潜水反射也是有效方法。", category: "SVT" },
  { id: "s37", question: "关于房室结折返性心动过速的发病率，以下哪项正确？", options: ["男性多于女性", "多见于老年人", "女性多于男性，多见于中年", "无性别差异"], correct: 2, explanation: "AVNRT 好发于中年女性，女性发病率约为男性的 2 倍。症状通常在 20-40 岁开始出现。与雌激素可能影响房室结传导特性有关。", category: "SVT" },
  { id: "s38", question: "以下哪种旁路位置在进行射频消融时最容易损伤冠状动脉？", options: ["左侧游离壁", "右侧游离壁", "心外膜旁路（冠状窦内/心中静脉内）", "前间隔旁路"], correct: 2, explanation: "心外膜旁路通常位于冠状窦（CS）内或心中静脉（MCV）内，消融时距离回旋支或右冠状动脉很近。需冠脉造影确认消融导管与冠脉的距离，冷冻消融可能更安全。", category: "SVT" },
  { id: "s39", question: "射频消融慢径改良术后，以下哪种情况下可以结束手术？", options: ["术中诱发一次非持续性 AVNRT", "心房程序刺激不能诱发 AVNRT，无慢径传导证据", "仅心房刺激不能诱发，未加异丙肾", "心动过速仍可诱发但频率减慢"], correct: 1, explanation: "慢径改良成功标准：① 房室结双径路现象消失或仅有慢径回波（< 2 个）② 不能诱发持续性 AVNRT ③ 异丙肾激发后仍不能诱发 ④ 无快径损伤导致的 PR 延长或 VA 阻滞。", category: "SVT" },
  { id: "s40", question: "关于妊娠期 SVT 的处理，以下哪项治疗在整个孕期均被视为安全？", options: ["维拉帕米静脉推注", "美托洛尔口服", "直流电复律", "射频消融"], correct: 2, explanation: "妊娠各阶段直流电复律均安全（胎儿心脏不受影响）。腺苷也可安全使用。维拉帕米和地尔硫卓在妊娠期应避免（可能胎儿心动过缓和低血压）。择期射频消融应推迟至产后（如需紧急消融，应在孕中期进行且尽量用零射线或超低射线）。", category: "SVT" },

  // ═══════════════════════════════════════════════════════════════
  // VT — 室性心动过速（30 题）
  // ═══════════════════════════════════════════════════════════════

  // 特发性 VT
  { id: "v01", question: "以下哪项是特发性室速最常见的类型？", options: ["ARVC 相关 VT", "缺血性心肌病 VT", "右室流出道 VT（RVOT-VT）", "束支折返性 VT"], correct: 2, explanation: "RVOT-VT 是特发性 VT 最常见类型，占 60-80%。通常为腺苷敏感性（cAMP 介导的触发活动）。心电图呈 LBBB 形态 + 下壁导联高大 R 波。", category: "VT" },
  { id: "v02", question: "RVOT-VT 发作时的心电图特征为？", options: ["RBBB + 电轴右偏", "LBBB + 下壁导联高大 R 波", "LBBB + 电轴左偏", "RBBB + 胸前导联 QS 型"], correct: 1, explanation: "RVOT-VT：起源于右室流出道，激动从上向下、从右向左传导 → LBBB 形态（V1 导联 QS/rS）+ 下壁导联（II、III、aVF）高大 R 波。胸前移行通常在 V3-V4。", category: "VT" },
  { id: "v03", question: "关于左室特发性 VT（ILVT / Belhassen VT），以下哪项描述正确？", options: ["腺苷可终止", "起源于左室流出道", "维拉帕米敏感，呈 RBBB + 电轴左偏", "消融靶点在右室"], correct: 2, explanation: "ILVT（Belhassen VT）：维拉帕米敏感，心电图呈 RBBB + 电轴左偏（左后分支区域起源）。机制为分支内折返（涉及 Purkinje 纤维）。靶点：左室间隔中下部记录到 Purkinje 电位（P电位）。", category: "VT" },
  { id: "v04", question: "Belhassen VT（维拉帕米敏感性左室特发 VT）的消融靶点是？", options: ["右室流出道", "左室流出道", "左后分支区域的 Purkinje 电位（P 电位）", "冠状窦内"], correct: 2, explanation: "ILVT 消融靶点：在左室间隔中下部记录到比 QRS 提前 15-30ms 的高频 Purkinje 电位（P 电位）。机械损伤（导管碰触）可终止 VT 也具有诊断价值。消融成功率高（> 90%）。", category: "VT" },
  { id: "v05", question: "关于儿茶酚胺敏感性多形性 VT（CPVT），以下哪项正确？", options: ["静息心电图通常正常", "与 RyR2 或 CASQ2 基因突变相关", "β 受体阻滞剂是首选治疗", "以上都正确"], correct: 3, explanation: "CPVT 特征：静息 ECG 正常，运动/情绪诱发双向或多形性 VT。最常见 RyR2 突变（AD 遗传）或 CASQ2 突变（AR 遗传）。治疗：β 受体阻滞剂（纳多洛尔首选）+ 运动限制 + 必要时 ICD/左心交感神经切除术。", category: "VT" },

  // 缺血性 / 结构性心脏病 VT
  { id: "v06", question: "缺血性心肌病患者室速的最常见机制是？", options: ["触发活动（cAMP 介导）", "自律性增高", "瘢痕相关折返", "触发活动（早期后除极）"], correct: 2, explanation: "缺血性心肌病 VT 主要机制为瘢痕内/边缘区存活心肌形成的折返环。瘢痕组织形成缓慢传导通路，为折返提供解剖基础。这是基质标测消融的理论基础。", category: "VT" },
  { id: "v07", question: "关于 VT 消融的基质标测，以下哪项描述是正确的？", options: ["只需在窦律下标测", "需要识别低电压区、晚电位和碎裂电位", "只适用于可诱发的 VT", "无法在血流动力学不稳定时进行"], correct: 1, explanation: "基质标测（substrate mapping）在窦性心律下进行：① 低电压区（双极电压 < 1.5mV 或 < 0.5mV 为致密瘢痕）② 晚电位（LP）③ 碎裂电位 ④ 起搏标测识别出口。可消融所有潜在的 VT 峡部，不依赖 VT 诱发。", category: "VT" },
  { id: "v08", question: "关于 VT 消融中晚电位（late potential, LP）的意义，以下哪项正确？", options: ["LP 位于瘢痕核心区，无消融价值", "LP 代表瘢痕内残存心肌的延迟传导，是 VT 峡部的标志", "LP 仅在心动过速时可见", "LP 与 VT 无关"], correct: 1, explanation: "晚电位（LP）位于 QRS 波后的低振幅信号，代表瘢痕内残存心肌束的缓慢传导，常为 VT 折返环的峡部。LP 消融消除（LPAO，late potential abolition）是 VT 消融的重要终点。", category: "VT" },
  { id: "v09", question: "关于 VT 风暴（electrical storm）的处理，以下哪项为首选？", options: ["射频消融", "抗心律失常药物 + 镇静 + 纠正诱因", "ICD 程控关闭抗心动过速起搏", "交感神经节阻滞"], correct: 1, explanation: "VT 风暴（24h 内 ≥3 次持续性 VT）的处理原则：① 紧急控制发作（β 受体阻滞剂 + 胺碘酮 + 镇静）② 纠正诱因（电解质、缺血、心衰）③ ICD 程控优化（延长检测时间，避免不适当电击）④ 药物难治者尽早消融或自主神经干预。", category: "VT" },
  { id: "v10", question: "ARVC 患者 VT 最常起源于哪个部位？", options: ["左室流出道", "右室流入道/心尖部/流出道（\"发育不良三角\"）", "左室心尖部", "室间隔"], correct: 1, explanation: "ARVC 最常见于右室的\"发育不良三角\"：右室流入道、右室心尖部和右室流出道。VT 通常起源于这些区域的瘢痕边缘。疾病进展可累及左室。", category: "VT" },

  // 宽 QRS 鉴别
  { id: "v11", question: "Brugada 四步法中，第一步是检查什么？", options: ["房室分离", "胸前导联是否有 RS 波", "RS 间期是否 > 100ms", "QRS 宽度是否 > 140ms"], correct: 1, explanation: "Brugada 四步法（1991）：① 胸前导联均无 RS 波 → VT（否则下一步）② RS 间期 > 100ms → VT（否则下一步）③ 房室分离 → VT（否则下一步）④ V1-V2 和 V6 导联 QRS 形态符合 VT 标准。", category: "VT" },
  { id: "v12", question: "关于 VT 与 SVT 合并差传的鉴别，Vereckei 算法（aVR 导联法）的第一步是？", options: ["QRS 宽度", "aVR 导联初始 R 波", "房室分离", "RS 间期"], correct: 1, explanation: "Vereckei aVR 算法（2008）：① aVR 导联起始为 R 波 → VT ② aVR 导联 r 波或 q 波宽度 > 40ms → VT ③ 负向 QRS 起始降支有切迹 → VT ④ Vi/Vt ≤ 1 → VT。简单快速。", category: "VT" },
  { id: "v13", question: "在宽 QRS 波心动过速中，以下哪项高度提示为 VT？", options: ["QRS 宽度 130ms", "电轴极度右偏（-90° ~ ±180°，\"西北\"电轴）", "QRS 呈典型 RBBB 形态", "Valsalva 可终止"], correct: 1, explanation: "\"西北\"电轴（-90° ~ ±180°）——即 I 和 aVF 导联均负向——高度提示 VT。正常心室激动和 SVT 合并差传几乎不可能出现此电轴。", category: "VT" },
  { id: "v14", question: "关于宽 QRS 心动过速，房室分离的诊断价值是？", options: ["房室分离是 SVT 的特征", "房室分离对 VT 的诊断特异性接近 100%", "房室分离只见于加速性室性心律", "房室分离无诊断价值"], correct: 1, explanation: "房室分离（P 波与 QRS 无关，心房率 < 心室率）是 VT 的标志性特征，特异性接近 100%。但仅 25-30% 的 VT 能在体表心电图上观察到房室分离。融合波和夺获波同样是 VT 的特异性指标。", category: "VT" },

  // VT 消融与预后
  { id: "v15", question: "哪项试验证实了 VT 消融对缺血性心肌病患者改善预后的价值？", options: ["CAST 试验", "VANISH 试验", "SMASH-VT 试验", "RAFT 试验"], correct: 1, explanation: "VANISH 试验（2016，NEJM）：缺血性心肌病合并 VT 患者，导管消融在减少死亡、VT 风暴和适当 ICD 治疗方面优于升级抗心律失常药物。SMASH-VT（2007）是最早证实预防性 VT 消融价值的 RCT。", category: "VT" },
  { id: "v16", question: "关于心外膜 VT 消融的指征，以下哪项最支持需经心外膜途径？", options: ["所有特发性 VT", "心内膜标测无合适靶点 + 心电图提示心外膜起源", "消融术中发生心包积液", "患者合并心包炎"], correct: 1, explanation: "心外膜消融指征：① 心内膜标测/消融失败 ② ECG 提示心外膜起源（假性 delta 波 > 34ms、MDI > 0.55）③ 致心律失常基质位于心外膜（如 ARVC、Chagas 病）。经皮剑突下穿刺（Sosa 技术）为标准入路。", category: "VT" },
  { id: "v17", question: "关于心肌病 VT 消融中使用心内超声（ICE）的主要优势，以下哪项最重要？", options: ["替代三维标测系统", "实时监测心包积液和导管-组织贴靠", "降低射线暴露", "替代程序刺激"], correct: 1, explanation: "ICE 在 VT 消融中主要用于：① 心外膜穿刺引导和心包积液实时监测 ② 导管-组织贴靠评估 ③ 乳头肌/调节束 VT 的解剖定位 ④ 监测消融过程中的并发症。ICE 不能替代三维标测系统，两者互补。", category: "VT" },

  // 特殊 VT 类型
  { id: "v18", question: "关于束支折返性 VT（BBR-VT），以下哪项描述正确？", options: ["通常见于正常心脏", "折返环利用左右束支作为折返路径", "维拉帕米敏感", "消融靶点在心室肌"], correct: 1, explanation: "BBR-VT 折返环：沿右束支前传 → 左束支逆传（呈 LBBB 形态），或反向（呈 RBBB 形态）。最常见于扩张型心肌病伴希浦系统病变。消融靶点：右束支（消融后可治愈但需评估起搏器需求）。", category: "VT" },
  { id: "v19", question: "关于运动诱发性 VT，以下哪种类型的 VT 最常被运动诱发？", options: ["缺血性 VT", "RVOT-VT 和 CPVT", "束支折返性 VT", "心肌梗死后瘢痕 VT"], correct: 1, explanation: "运动/儿茶酚胺最常诱发：RVOT-VT（触发活动，腺苷敏感）、CPVT（双向/多形性 VT）、左室流出道 VT。缺血性 VT 也常在运动时诱发。瘢痕折返性 VT 可能随机发生。", category: "VT" },
  { id: "v20", question: "关于致心律失常性右室心肌病（ARVC）的 2010 Task Force 诊断标准，以下哪项是主要标准？", options: ["epsilon 波（右胸导联 QRS 后小波）", "V1-V3 导联 T 波倒置（>14 岁）", "右室造影显示右室运动障碍/室壁瘤", "以上都是"], correct: 3, explanation: "ARVC 诊断需 ≥2 项主要标准或 1 项主要 + 2 项次要或 4 项次要。主要标准包括：epsilon 波、V1-V3 T 波倒置、影像学右室运动异常/室壁瘤、心内膜活检纤维脂肪替代、尸检或手术证实。", category: "VT" },
  { id: "v21", question: "流出道 VT 最早激动点标测中，理想靶点的局部电位应比 QRS 起始提前多少？", options: ["10-20 ms", "> 30 ms", "> 100 ms", "与 QRS 起始同步"], correct: 1, explanation: "流出道 VT 理想靶点：局部电位比体表 QRS 起始提前 ≥30ms。同时起搏标测应尽量达到 12 导联匹配（至少 11/12）。单极电图 QS 形态提示激动从该点向外辐射。", category: "VT" },
  { id: "v22", question: "关于 LQTS（长 QT 综合征）相关尖端扭转型室速（TdP），以下哪项是禁忌？", options: ["静脉补镁", "临时起搏（提高心率）", "静脉注射胺碘酮", "β 受体阻滞剂"], correct: 2, explanation: "获得性 LQTS 合并 TdP 时，禁用延长 QT 间期的药物——包括胺碘酮、索他洛尔、伊布利特等。TdP 急性处理：停用致 QT 延长药物 + 补镁 + 补钾 + 临时起搏（提高心率至 100-120 bpm，缩短 QT）。", category: "VT" },
  { id: "v23", question: "关于特发性室颤（IVF），以下哪项正确？", options: ["心电图和影像学均正常", "与 SCN5A 突变无关", "ICD 是唯一治疗选择", "预后与心肌梗死后 VT 相同"], correct: 0, explanation: "IVF 诊断标准：发生 VF 且心电图、影像学、冠脉造影均正常，排除已知离子通道病。可能为隐匿性心肌病早期或未知突变。治疗：ICD 植入（二级预防），部分病例可以考虑消融触发灶（Purkinje 早搏）。", category: "VT" },
  { id: "v24", question: "关于扩张型心肌病瘢痕 VT，以下哪种标测策略是最常用的？", options: ["仅起搏标测", "仅激动标测", "基质标测（低电压区 + 晚电位）联合起搏标测和拖带标测", "仅拖带标测"], correct: 2, explanation: "DCM 瘢痕 VT 的标测策略是多种方法的整合：① 窦律下基质标测（低电压区、晚电位）② VT 发作时激动标测和拖带标测（血流动力学稳定的情况下）③ 起搏标测确认 ④ 消融晚电位和 VT 峡部。", category: "VT" },
  { id: "v25", question: "关于血流动力学不稳定的 VT，以下哪种消融策略可在不诱发 VT 的情况下完成消融？", options: ["仅依赖拖带标测", "基质改良消融（substrate modification）", "必须使用体外循环支持", "无法进行消融"], correct: 1, explanation: "对于血流动力学不稳定的 VT，可在窦律下行基质改良消融：识别低电压区和晚电位 → 消融所有可能的 VT 峡部（LPAO 策略）→ 术后程序刺激验证。研究表明基质消融可显著减少 VT 复发。", category: "VT" },
  { id: "v26", question: "以下哪种疾病最常合并心外膜 VT 基质？", options: ["特发性 RVOT-VT", "ARVC 和 Chagas 心肌病", "Belhassen VT", "CPVT"], correct: 1, explanation: "ARVC 和 Chagas 病（美洲锥虫病）的致心律失常基质常位于心外膜，心外膜消融可显著提高消融成功率。非缺血性心肌病（特别是 LMNA 突变相关）也常需心外膜消融。", category: "VT" },
  { id: "v27", question: "关于 ICD 一级预防在缺血性心肌病中的应用，以下哪项 LVEF 阈值为 I 类推荐？", options: ["LVEF ≤ 50%", "LVEF ≤ 35%（NYHA II-III 级，优化药物治疗 ≥3 个月）", "LVEF ≤ 45%", "LVEF ≤ 25%"], correct: 1, explanation: "指南推荐：缺血性心肌病 LVEF ≤ 35% + NYHA II-III 级 + 优化药物治疗 ≥3 个月（或心梗后 ≥40 天）+ 预期生存 > 1 年 → ICD 一级预防（I 类）。MADIT-II 和 SCD-HeFT 试验支持。", category: "VT" },
  { id: "v28", question: "关于抗心动过速起搏（ATP）终止 VT，以下哪项正确？", options: ["ATP 对所有 VT 都有效", "ATP 可终止约 70-90% 的瘢痕折返性 VT，避免电击", "ATP 增加晕厥风险", "ATP 在线索治疗中无效"], correct: 1, explanation: "ATP（burst 或 ramp 起搏）可无痛终止大部分瘢痕折返性 VT（70-90%），避免不适当电击。PainFREE 和 PREPARE 试验证实 ATP 策略安全有效。ATP 可能加速 VT（少见），此时需备用电击。", category: "VT" },
  { id: "v29", question: "以下哪项不是 ICD 植入的并发症？", options: ["气胸", "导线断裂/绝缘层破损", "心脏压塞", "降低房颤发生率"], correct: 3, explanation: "ICD 植入的并发症包括：气胸、血胸、心脏压塞、导线脱位/断裂/感染、不适当电击。ICD 不能降低房颤发生率。不适当电击（常因房颤快速心室率被误判为 VT）是最常见也最影响生活质量的并发症。", category: "VT" },
  { id: "v30", question: "关于左室流出道 VT（LVOT-VT）与 RVOT-VT 的鉴别，以下哪项有助于诊断 LVOT 起源？", options: ["LBBB 形态", "V1 导联 R 波时限 > QRS 的 50% 或 R/S > 1", "下壁导联 QS 型", "胸前移行在 V1-V2"], correct: 1, explanation: "LVOT-VT：起源在主动脉瓣上或瓣下，激动更早到达左室，V1 导联 R 波更明显（R 波时限 > 50% QRS 或 R/S ≥ 1）。RVOT-VT：V1 导联通常呈 QS 或 rS 形态，胸前移行在 V3-V4。", category: "VT" },

  // ═══════════════════════════════════════════════════════════════
  // AF — 心房颤动（25 题）
  // ═══════════════════════════════════════════════════════════════

  { id: "a01", question: "房颤导管消融的主要靶点是？", options: ["房室结", "希氏束", "肺静脉", "冠状窦"], correct: 2, explanation: "肺静脉是房颤触发灶最常见来源，肺静脉隔离（PVI）是房颤导管消融的基石。Haissaguerre 等 1998 年首次报道肺静脉触发房颤。", category: "AF" },
  { id: "a02", question: "关于肺静脉隔离（PVI）消融终点，以下哪项是公认标准？", options: ["肺静脉内电位振幅降低 > 50%", "肺静脉-左房传入和传出阻滞（双向阻滞）", "消融后不能诱发房颤", "PVI 后等待 10 分钟即可"], correct: 1, explanation: "PVI 标准终点：肺静脉-左房传入阻滞（肺静脉电位消失或分离）和传出阻滞（肺静脉内起搏不能夺获心房）。需用环状标测导管验证。腺苷/异丙肾激发可发现急性再连接。", category: "AF" },
  { id: "a03", question: "关于房颤导管消融术后 3 个月空白期，以下哪项处理是正确的？", options: ["立即二次消融", "药物控制 + 观察（炎症/水肿消退）", "永久性起搏器植入", "立即电复律"], correct: 1, explanation: "术后 3 个月为空白期（blanking period），此期间房性心律失常不代表消融失败。原因：消融灶炎症/水肿、自主神经功能紊乱。推荐药物控制（可用原抗心律失常药或胺碘酮过渡），3 个月后再评估。", category: "AF" },
  { id: "a04", question: "以下哪项 CHA₂DS₂-VASc 评分组合达到启动抗凝的推荐标准？", options: ["男性 0 分", "男性 ≥2 分或女性 ≥3 分", "女性 0 分", "仅年龄 65-74 岁一项"], correct: 1, explanation: "2024 ESC 指南：男性 CHA₂DS₂-VASc ≥2、女性 ≥3 → 推荐抗凝（I 类）。男性 =1、女性 =2 → 应考虑抗凝（IIa 类）。建议使用 NOAC 优于华法林（I 类，除非机械瓣或中重度二尖瓣狭窄）。", category: "AF" },
  { id: "a05", question: "房颤合并肥厚型心肌病患者，抗凝推荐基于什么？", options: ["仅 CHA₂DS₂-VASc 评分", "无论 CHA₂DS₂-VASc 评分，一经诊断房颤即推荐终身抗凝", "仅 HAS-BLED 评分 ≤2", "无需抗凝"], correct: 1, explanation: "HCM 患者一旦诊断房颤，无论 CHA₂DS₂-VASc 评分多少均推荐终身抗凝（2024 ESC HCM 指南 I 类推荐）。HCM 患者房颤卒中风险极高（年发生率 3-5%）。", category: "AF" },
  { id: "a06", question: "关于房颤的节律控制 vs 心率控制，EAST-AFNET 4 试验（2020）的核心结论是？", options: ["心率控制优于节律控制", "早期节律控制（诊断 1 年内）可降低心血管死亡和卒中风险", "节律控制只对老年人有效", "两者无差异"], correct: 1, explanation: "EAST-AFNET 4（2020，NEJM）：早期节律控制（诊断 1 年内，主要用氟卡尼和胺碘酮，部分消融）相比常规治疗，降低心血管死亡、卒中、心衰住院复合终点 21%。2024 ESC 指南因此将早期节律控制提升为 I 类推荐。", category: "AF" },
  { id: "a07", question: "关于房颤导管消融的并发症，以下哪项是心包积液/心脏压塞的典型早期表现？", options: ["ST 段抬高", "血压下降 + 心率增快 + 心音遥远", "QRS 增宽", "高度房室传导阻滞"], correct: 1, explanation: "心脏压塞（发生率 0.5-1%）：血压下降、心率增快（Beck 三联征：低血压 + 颈静脉怒张 + 心音遥远）。ICE 可实时监测。紧急心包穿刺引流可挽救生命。术后迟发压塞（数小时后）也需警惕。", category: "AF" },
  { id: "a08", question: "关于冷冻球囊消融治疗房颤，与射频消融相比以下哪项是正确的？", options: ["肺静脉狭窄发生率更高", "对膈神经损伤的风险可忽略", "单次消融实现 PVI 的效率高，学习曲线较短", "只适用于阵发性房颤"], correct: 2, explanation: "冷冻球囊的优势：① 操作相对标准化，学习曲线短 ② 单次冷冻即可实现环形 PVI ③ 血栓事件低于射频。劣势：膈神经损伤风险（右侧肺静脉消融时）、不适用于所有肺静脉解剖变异。STOP-AF 和 FIRE AND ICE 试验证实其非劣效于射频。", category: "AF" },
  { id: "a09", question: "FIRE AND ICE 试验（2016）比较冷冻球囊与射频消融治疗阵发性房颤，主要结论是？", options: ["射频优于冷冻", "冷冻优于射频", "两者在有效性和安全性方面无显著差异", "冷冻球囊组卒中发生率更高"], correct: 2, explanation: "FIRE AND ICE（2016，NEJM）：冷冻球囊与射频消融治疗药物难治性阵发性房颤，在主要有效性终点（房性心律失常复发）和安全性终点方面均无显著差异。冷冻球囊组膈神经损伤更多见。", category: "AF" },
  { id: "a10", question: "以下哪种新型口服抗凝药（NOAC）在 CRCL < 15 ml/min 或透析患者中是禁忌的？", options: ["阿哌沙班", "利伐沙班", "达比加群", "以上 NOAC 在 CRCL < 15 ml/min 时均禁忌/缺乏证据"], correct: 3, explanation: "NOAC 在严重肾功能不全中的应用：达比加群 CRCL < 30 禁用，利伐沙班和阿哌沙班 CRCL < 15 禁用。CRCL 15-30 时可考虑减量阿哌沙班（2.5mg bid）或利伐沙班（15mg qd）。透析患者：阿哌沙班可考虑（美国），但证据有限。华法林在透析中安全可用。", category: "AF" },
  { id: "a11", question: "关于左心耳封堵（LAAC），以下哪项描述正确？", options: ["适用于所有房颤患者", "适用于高卒中风险且长期抗凝有禁忌者", "可替代房颤消融", "预防房颤复发"], correct: 1, explanation: "LAAC（Watchman、Amplatzer Amulet 等）适应证：CHA₂DS₂-VASc ≥2（男）/≥3（女）+ 长期抗凝禁忌（如反复大出血/出血高风险）。PROTECT-AF 和 PREVAIL 试验证实其非劣效于华法林，且出血性卒中更少。", category: "AF" },
  { id: "a12", question: "以下哪项抗心律失常药在房颤合并 LVEF < 40% 或心衰患者中相对安全？", options: ["氟卡尼", "普罗帕酮", "胺碘酮", "索他洛尔"], correct: 2, explanation: "CAST 试验证实 I 类抗心律失常药增加心梗后死亡率。对于结构性心脏病/心衰：胺碘酮安全可用（不增加死亡率）；多非利特也是安全选项。决奈达隆在 NYHA IV 级/近期失代偿心衰中禁忌（ANDROMEDA 试验）。", category: "AF" },
  { id: "a13", question: "房颤合并预激综合征（WPW）时，以下哪种药物应绝对避免？", options: ["伊布利特", "普鲁卡因胺", "地高辛或维拉帕米", "氟卡尼"], correct: 2, explanation: "WPW 合并房颤时，阻断房室结的药物（地高辛、维拉帕米/地尔硫卓、腺苷、β 受体阻滞剂）可促进激动经旁路快速下传 → 可能诱发室颤。应使用阻断旁路的药物（伊布利特、普鲁卡因胺）或直接电复律。", category: "AF" },
  { id: "a14", question: "关于房颤的上游治疗（upstream therapy），以下哪项有循证证据支持？", options: ["ACEI/ARB 预防新发房颤（心衰/高血压患者中）", "鱼油（omega-3）预防房颤复发", "维生素 C 预防术后房颤", "他汀类药物预防房颤消融后复发"], correct: 0, explanation: "上游治疗（预防房颤基质形成）：ACEI/ARB 在心衰和高血压患者中可减少新发房颤。其他上游治疗（他汀、鱼油、醛固酮拮抗剂）在 RCT 中未显示预防房颤复发或新发的获益。", category: "AF" },
  { id: "a15", question: "关于心率控制治疗房颤的目标心率，RACE II 试验支持以下哪项？", options: ["严格心率控制（静息 < 60 bpm）", "宽松心率控制（静息 < 110 bpm）", "心率控制目标为运动时 < 130 bpm", "所有患者心率控制都优于节律控制"], correct: 1, explanation: "RACE II（2010，NEJM）：永久性房颤心率控制，宽松策略（静息心率 < 110 bpm）不劣于严格策略（静息 < 80 + 中度运动 < 110），且宽松组就诊次数更少。2024 ESC 指南推荐初始心率控制目标为静息 < 110 bpm，如仍有症状可更严格。", category: "AF" },
  { id: "a16", question: "以下哪项房颤消融后房性心动过速（AT）最常见？", options: ["典型房扑（CTI 依赖）", "围绕 PVI 瘢痕的折返性 AT（gap-related flutter）", "自律性房速", "窦房结折返性心动过速"], correct: 1, explanation: "PVI 后 AT 最常见为 PVI 线 gap 相关的大折返性房扑（围绕同侧肺静脉或沿顶部线/底部线）。导管消融（通常重新隔离 PVI 线性消融）可治愈。其次为典型房扑（原已存在的 CTI 依赖房扑显现）。", category: "AF" },
  { id: "a17", question: "关于持续性房颤的消融策略，以下哪项在 STAR-AF II 试验中显示额外获益？", options: ["仅 PVI", "PVI + 线性消融（顶部线 + 二尖瓣峡部线）", "PVI + 碎裂电位（CFAE）消融", "PVI 基础上增加线性消融或 CFAE 消融未显示优于单纯 PVI"], correct: 3, explanation: "STAR-AF II（2015，NEJM）：对于持续性房颤，PVI + 线性消融或 CFAE 消融相比单纯 PVI 未进一步降低房颤复发率，且手术时间和射线量增加。目前仍以 PVI 为持久性房颤的标准消融术式（+ 酌情线性消融）。", category: "AF" },
  { id: "a18", question: "关于房颤的流行病学，以下哪项描述是正确的？", options: ["房颤的终生风险约为 1%", "房颤发病率随年龄增加，80 岁以上患病率约 10%", "亚洲人群房颤患病率高于欧美", "男性房颤风险低于女性"], correct: 1, explanation: "房颤是最常见的持续性心律失常。Framingham 研究：40 岁以上终生风险约 25%。80 岁以上人群患病率约 10%。欧美国家患病率高于亚洲。男性风险高于女性。主要危险因素：年龄、高血压、肥胖、心衰、糖尿病。", category: "AF" },
  { id: "a19", question: "关于决奈达隆（dronedarone），以下哪项正确描述了其禁忌证？", options: ["可用于 NYHA IV 级心衰", "可用于永久性房颤", "失代偿心衰或 NYHA III-IV 级且近期失代偿者禁用", "无肝功能监测要求"], correct: 2, explanation: "ANDROMEDA 试验（2007）：决奈达隆在 NYHA III-IV 级或近期失代偿心衰患者中增加死亡率（因心衰恶化）→ 禁忌。PALLAS 试验（2011）：永久性房颤患者中增加心衰、卒中和心血管死亡 → 禁忌。适用于阵发性/持续性房颤、LVEF 正常的患者（ATHENA 试验获益）。", category: "AF" },
  { id: "a20", question: "关于房颤患者卒中预防，以下哪种情况推荐使用华法林而非 NOAC？", options: ["非瓣膜性房颤合并高血压", "机械瓣置换术后合并房颤", "阵发性房颤", "老年患者（> 75 岁）"], correct: 1, explanation: "机械瓣（特别是二尖瓣机械瓣）合并房颤时，NOAC 不适用（RE-ALIGN 试验显示达比加群增加血栓和出血事件）。华法林（目标 INR 2.5-3.5）是机械瓣的标准抗凝方案。中重度二尖瓣狭窄也推荐华法林（缺乏 NOAC 证据）。", category: "AF" },
  { id: "a21", question: "关于房颤消融术后停用抗凝的问题，以下哪项描述符合当前指南推荐？", options: ["消融成功后立即停用抗凝", "无论消融是否成功，术后终身抗凝", "根据 CHA₂DS₂-VASc 评分决定，不能仅因消融成功而在高危患者中停用抗凝", "所有患者消融后 3 个月常规停用抗凝"], correct: 2, explanation: "指南推荐：抗凝决策基于卒中风险（CHA₂DS₂-VASc 评分），而非消融是否成功或心律状态。高风险患者即使消融后维持窦律也应继续抗凝（隐匿性房颤复发率仍存在）。低风险患者（男性 0、女性 1）消融后可不抗凝。", category: "AF" },
  { id: "a22", question: "以下哪项是房颤患者进行经食道超声心动图（TEE）的主要目的？", options: ["评估左室功能", "排除左心耳血栓", "测量肺动脉压力", "评估二尖瓣反流程度"], correct: 1, explanation: "房颤电复律或消融前 TEE 的主要目的是排除左心耳血栓。TEE 阴性者可在肝素化后安全行电复律/消融，避免 3-4 周术前抗凝等待。左心耳血栓阳性者需抗凝 ≥ 3 周后复查 TEE 确认血栓消失。", category: "AF" },
  { id: "a23", question: "关于房颤的导管消融能量源，以下哪项正在进行大规模临床评估？", options: ["射频能量", "冷冻球囊", "脉冲电场消融（PFA, pulsed field ablation）", "微波消融"], correct: 2, explanation: "脉冲电场消融（PFA，如 Farapulse、VARIPULSE 等）是房颤消融的新兴技术，利用短时高压电脉冲不可逆电穿孔心肌细胞。优势：组织选择性（心肌 > 神经/食管/冠脉），减少膈神经损伤、肺静脉狭窄和食管瘘风险。PULSED AF 等试验已证实其有效性和安全性，已获 FDA 批准。", category: "AF" },
  { id: "a24", question: "关于房颤患者使用抗凝药的出血风险评估，HAS-BLED 评分 ≥ 3 分的处理是？", options: ["停止抗凝", "无需特殊处理", "纠正好正的可逆危险因素 + 更密切的随访监测", "换用阿司匹林"], correct: 2, explanation: "HAS-BLED ≥ 3 分表示高出血风险，但不意味着应停用抗凝——卒中风险仍可能超过出血风险。处理：① 纠正可控因素（血压、INR 控制、避免 NSAIDs/抗血小板、限酒）② 更频繁的随访监测 ③ 评估左心耳封堵的可行性。", category: "AF" },
  { id: "a25", question: "房颤患者进行心脏复律时，如果房颤持续时间不明确或 > 48h，以下哪项策略是正确的？", options: ["立即电复律", "TEE 排除左心耳血栓后立即复律（TEE 指导策略）", "无需任何准备直接复律", "服阿司匹林后复律"], correct: 1, explanation: "房颤持续时间 > 48h 或未知时，有两种策略：① TEE 指导策略：TEE 排除左心耳血栓 → 肝素化后立即复律 → 术后抗凝 ≥ 4 周 ② 传统策略：有效抗凝 ≥ 3 周 → 复律 → 术后抗凝 ≥ 4 周。两种策略血栓栓塞风险无差异。", category: "AF" },

  // ═══════════════════════════════════════════════════════════════
  // AFL — 心房扑动（12 题）
  // ═══════════════════════════════════════════════════════════════

  { id: "l01", question: "典型心房扑动的折返环位于？", options: ["左心房后壁", "肺静脉口", "三尖瓣-下腔静脉峡部（CTI）", "冠状窦口"], correct: 2, explanation: "典型 AFL 折返环位于右心房三尖瓣-下腔静脉峡部（CTI）。逆钟向折返（下壁导联负向 F 波）占 90%，顺钟向折返（下壁导联正向 F 波）占 10%。CTI 线性消融成功率 > 95%。", category: "AFL" },
  { id: "l02", question: "关于典型 AFL 的体表心电图特征，以下哪项描述正确？", options: ["心房率 150 bpm", "P 波明显，PR 间期正常", "锯齿状扑动波（F 波），下壁导联明显，心房率 250-350 bpm", "P 波形态多变"], correct: 2, explanation: "典型 AFL 心电图特征：锯齿状扑动波（F 波），下壁导联（II、III、aVF）最明显，心房率 250-350 bpm（通常约 300 bpm）。常伴 2:1 房室传导（心室率约 150 bpm）。F 波之间无等电位线。", category: "AFL" },
  { id: "l03", question: "关于 CTI 依赖房扑消融，以下哪项是公认的手术终点？", options: ["CTI 线消融完成即可", "房扑终止", "CTI 双向传导阻滞", "消融后 15 分钟不再诱发"], correct: 2, explanation: "CTI 双向阻滞是标准终点，验证方法：① 起搏 CS 近端时，低位右房侧壁激动顺序由下向上（逆钟向阻滞）② 起搏低位右房侧壁时，CS 激动由近到远（顺钟向阻滞）。仅房扑终止不足——房扑终止可能是一过性的。", category: "AFL" },
  { id: "l04", question: "关于非典型心房扑动，以下哪项描述是正确的？", options: ["折返环依赖 CTI", "下壁导联可见清晰的锯齿状 F 波", "折返环不依赖 CTI，通常与心房瘢痕/手术切口有关", "腺苷可终止"], correct: 2, explanation: "非典型 AFL 的折返环不依赖 CTI，通常围绕心房瘢痕区（如外科术后切口、消融后瘢痕、纤维化区域）形成大折返。心电图特征多变，F 波不典型。标测和消融需要使用三维电解剖标测系统。", category: "AFL" },
  { id: "l05", question: "房颤消融术后出现的房扑最常见类型是？", options: ["典型 CTI 依赖房扑", "围绕肺静脉 PVI 瘢痕的 gap 相关折返", "心房顶部依赖房扑", "窦房结折返"], correct: 1, explanation: "PVI 术后新发房扑大多数为 PVI 线 gap 相关的大折返（围绕同侧肺静脉或沿顶部线/底部线），其次为原已存在但之前被房颤掩盖的典型 CTI 依赖房扑。消融策略为标测 gap 并补点消融。", category: "AFL" },
  { id: "l06", question: "关于典型 AFL 的药物治疗，以下哪项正确？", options: ["腺苷可终止典型 AFL", "伊布利特转复典型 AFL 成功率较高（约 60%）", "维拉帕米可终止典型 AFL", "典型 AFL 对药物转复无效"], correct: 1, explanation: "伊布利特（III 类）转复典型 AFL 的成功率约 60-80%（高于房颤）。氟卡尼减慢心房率但可能导致 1:1 房室传导（需合用房室结阻断药）。腺苷不能终止 AFL 但可暴露扑动波（一过性房室阻滞）。", category: "AFL" },
  { id: "l07", question: "典型 AFL 发作时，心室率 150 bpm（心房率 300 bpm）说明？", options: ["存在 1:1 房室传导", "存在 2:1 房室传导", "存在高度房室传导阻滞", "使用了 β 受体阻滞剂"], correct: 1, explanation: "AFL 心房率约 300 bpm → 2:1 房室传导 → 心室率约 150 bpm。这是典型 AFL 最常见的传导比例。偶见 1:1 传导（如使用氟卡尼/普罗帕酮后或运动时）可导致血流动力学崩溃。", category: "AFL" },
  { id: "l08", question: "关于 CTI 消融的解剖边界，以下哪项描述正确？", options: ["三尖瓣环到下腔静脉口", "三尖瓣环到上腔静脉", "冠状窦口到肺静脉", "房间隔到下腔静脉"], correct: 0, explanation: "CTI 线：从三尖瓣环（心室侧）到下腔静脉口（心房侧）。消融导管通过下腔静脉进入右房，在 CTI 线上逐点消融形成线性阻滞。CTI 线完整是实现双向阻滞的解剖基础。", category: "AFL" },
  { id: "l09", question: "CTI 消融过程中，起搏 CS 近端时低位右房侧壁激动由下向上，这证实了什么？", options: ["顺钟向阻滞", "逆钟向阻滞（CTI 一侧阻滞）", "双向阻滞均已实现", "CTI 仍可传导"], correct: 1, explanation: "起搏 CS 近端（CS1-2）→ 激动无法经 CTI 传到低位右房侧壁 → 激动沿房间隔向上传到右房顶部 → 最后激动低位右房侧壁（由上向下激动）。低位右房侧壁冲动方向变为从下向上时 → 逆钟向阻滞成立。", category: "AFL" },
  { id: "l10", question: "关于 Ebstein 畸形合并房扑，以下哪项正确？", options: ["只能通过药物控制", "CTI 消融通常可根治，但解剖变异增加手术难度", "房扑来自左房", "ICD 是唯一治疗"], correct: 1, explanation: "Ebstein 畸形合并房扑通常是 CTI 依赖型，CTI 消融可根治。但 Ebstein 畸形患者 CTI 解剖变异大（三尖瓣环移位、心房化右室），手术难度增加。常合并右侧旁路和房颤。", category: "AFL" },
  { id: "l11", question: "以下哪种房扑属于\"大折返性房性心动过速\"的范畴？", options: ["仅典型 CTI 依赖 AFL", "典型 AFL + 非典型瘢痕依赖 AFL + 外科术后切口 AFL", "自律性房速", "房室折返性心动过速"], correct: 1, explanation: "\"大折返性 AT\"（macroreentrant AT）包括：典型 CTI 依赖 AFL、非典型瘢痕/切口相关 AFL、围绕消融线/补片的 AFL。共同特点：折返环直径 > 2cm，可通过拖带标测和三维标测定位关键峡部。", category: "AFL" },
  { id: "l12", question: "典型 AFL 如果不治疗，最可能的并发症是？", options: ["进展为房室传导阻滞", "持续快速心室率导致心动过速性心肌病", "室颤", "心肌梗死"], correct: 1, explanation: "持续 AFL 未控制心室率可导致心动过速性心肌病（tachycardia-induced cardiomyopathy）——心室率持续 > 100-120 bpm 数月可导致 LVEF 显著下降。有效控制心室率或恢复窦律后 LVEF 可完全恢复。血栓栓塞风险也需抗凝预防。", category: "AFL" },

  // ═══════════════════════════════════════════════════════════════
  // 综合 — EP 基础 / 药物 / 起搏器 / 离子通道病（25 题）
  // ═══════════════════════════════════════════════════════════════

  { id: "z01", question: "心脏电生理检查中，His 束电位的正常 HV 间期为？", options: ["10-20 ms", "35-55 ms", "80-120 ms", "150-200 ms"], correct: 1, explanation: "HV 间期正常范围 35-55 ms，代表从 His 束到心室肌的传导时间。HV < 35ms 可能提示心室预激（旁路前传）。HV > 55ms 或 > 100ms 提示希浦系统病变，进展为完全性房室传导阻滞风险增高。", category: "综合" },
  { id: "z02", question: "心脏电生理检查中，正常 AH 间期范围是？", options: ["10-30 ms", "50-130 ms", "150-250 ms", "> 250 ms"], correct: 1, explanation: "AH 间期正常 50-130 ms，代表从低位右房经房室结到 His 束的传导时间。AH 间期受自主神经张力影响明显（交感激活缩短，迷走激活延长）。AH > 130ms 提示房室结传导延迟。", category: "综合" },
  { id: "z03", question: "关于 Brugada 综合征，以下哪项描述正确？", options: ["心电图呈 LBBB 形态", "右胸导联 ST 段抬高，与 SCN5A 基因突变相关", "通常由缺血性心肌病引起", "首选治疗是 β 受体阻滞剂"], correct: 1, explanation: "Brugada 综合征特征：右胸导联（V1-V3）ST 段抬高（≥2mm，穹隆型或马鞍型），最常见与 SCN5A 突变（钠通道功能丧失）相关。ICD 是高危患者（晕厥/猝死生还）的唯一有效治疗。奎尼丁可用于 ICD 频繁电击或禁忌 ICD 者。", category: "综合" },
  { id: "z04", question: "Brugada 综合征 I 型心电图的特征性 ST 段抬高形态是？", options: ["马鞍型（saddleback）", "穹隆型（coved type），ST 段抬高 ≥2mm 后逐渐下降并倒置 T 波", "ST 段压低", "T 波高尖"], correct: 1, explanation: "Brugada I 型（诊断性）：穹隆型（coved）ST 段抬高 ≥2mm，随后逐渐下降至倒置 T 波，≥1 个右胸导联（V1-V3）。II 型：马鞍型（saddleback），抬高 ≥2mm（谷底 ≥1mm）。发热、钠通道阻滞剂（阿义马林/氟卡尼）可激发 I 型 ECG。", category: "综合" },
  { id: "z05", question: "关于长 QT 综合征（LQTS），以下哪项是 LQT2 型（HERG 突变）的典型心电图触发模式？", options: ["运动/游泳时发生心脏事件", "突然的声音刺激（如闹钟）或情绪应激诱发", "休息/睡眠时发生心脏事件", "餐后发生心脏事件"], correct: 1, explanation: "LQTS 基因型-表型关联：LQT1（KCNQ1 突变）→ 运动（特别是游泳）诱发；LQT2（HERG/KCNH2 突变）→ 突然声音刺激/情绪应激诱发；LQT3（SCN5A 突变）→ 睡眠/休息时发生。针对不同基因型的治疗策略不同。", category: "综合" },
  { id: "z06", question: "关于心脏钠通道阻滞剂在 Brugada 综合征诊断中的应用，以下哪项常用作激发药物？", options: ["异丙肾", "阿义马林（ajmaline）或氟卡尼", "维拉帕米", "腺苷"], correct: 1, explanation: "钠通道阻滞剂激发试验用于揭示隐匿性 Brugada ECG。阿义马林（国内不可及）、氟卡尼或普鲁卡因胺静脉给药，出现 I 型 ECG 为阳性。异丙肾用于 Brugada 心律失常风暴的急救（增加 L 型钙电流）。", category: "综合" },
  { id: "z07", question: "关于儿茶酚胺敏感性多形性 VT（CPVT），以下哪项治疗选择是一线推荐？", options: ["胺碘酮", "纳多洛尔（非选择性 β 受体阻滞剂）", "维拉帕米", "ICD 单独植入（无 β 受体阻滞剂）"], correct: 1, explanation: "CPVT 治疗：① 纳多洛尔（非选择性 β 受体阻滞剂）为一线药物 ② 氟卡尼可减少室性心律失常（尽管为 I 类药，但在 CPVT 中安全有效）③ 左心交感神经切除术（LCSD）用于药物难治性 ④ ICD 仅用于优化药物后仍有晕厥/VF 者（ICD 电击可能触发交感风暴）。", category: "综合" },
  { id: "z08", question: "关于短 QT 综合征（SQTS），以下哪项诊断标准是正确的？", options: ["QTc < 360ms", "QTc < 340ms 或 ≤ 320ms（有症状者）", "QTc > 460ms", "QTc < 400ms"], correct: 1, explanation: "SQTS 诊断：QTc ≤ 340ms 或 QTc ≤ 360ms + 致病突变/晕厥/VF 家族史/生还 VF。2015 ESC 指南：QTc ≤ 320ms 为肯定诊断。SQTS 与钾通道功能获得性突变（KCNH2、KCNQ1、KCNJ2）相关。ICD 是猝死二级预防的唯一有效治疗。奎尼丁可延长 QT 间期。", category: "综合" },
  { id: "z09", question: "关于拖带（entrainment）标测，以下哪项描述是正确的？", options: ["拖带只能在窦性心律下进行", "隐匿性融合（concealed fusion）提示起搏部位在折返环内", "PPI-TCL > 30ms 提示起搏部位在折返环内", "拖带不能用于房扑标测"], correct: 1, explanation: "隐匿性融合：起搏不改变心动过速的 P/QRS 形态和心内激动顺序，说明起搏部位在折返环的保护峡部内（周围被解剖屏障保护）。PPI（起搏后间期）- TCL（心动过速周长）< 30ms 提示起搏部位在折返环内。", category: "综合" },
  { id: "z10", question: "关于三维电解剖标测系统（如 Carto、EnSite），以下哪项不是其主要功能？", options: ["电解剖图（电压图/激动图）", "实时导管定位（无射线或低射线）", "自动消融靶点识别", "心腔三维模型重建"], correct: 2, explanation: "三维标测系统（Carto、EnSite、Rhythmia）功能：① 心腔三维解剖重建 ② 电解剖图（电压图显示瘢痕、激动图显示传播、碎裂电图等）③ 实时导管定位减少射线 ④ 消融点标记。系统不自动识别消融靶点——需术者分析判断。", category: "综合" },
  { id: "z11", question: "关于起搏器模式，DDD 模式的第一个 D 代表什么？", options: ["心房感知", "心房起搏", "双腔（心房和心室）", "频率应答"], correct: 1, explanation: "NBG 起搏器编码（NASPE/BPEG）：第一位 = 起搏心腔（A/V/D），第二位 = 感知心腔（A/V/D），第三位 = 感知后反应（I=抑制/T=触发/D=双）。DDD = 双腔起搏 + 双腔感知 + 双反应。DDDR = DDD + 频率应答（R）。", category: "综合" },
  { id: "z12", question: "关于起搏器综合征，以下哪项描述正确？", options: ["由起搏器感染引起", "VVI 起搏时心房收缩恰逢房室瓣关闭 → 血压下降、心悸、头晕", "只见于 DDD 起搏模式", "必须手术取出起搏器"], correct: 1, explanation: "起搏器综合征发生于 VVI/VVIR 起搏（心室单腔起搏），因房室失同步导致：心房收缩时房室瓣关闭 → 心房压力增高（\"大炮A波\"）→ 血压下降、心悸、头晕、颈静脉怒张。治疗：升级为 DDD 起搏器恢复房室同步。", category: "综合" },
  { id: "z13", question: "关于左束支区域起搏（LBBAP），以下哪项描述正确？", options: ["等同于传统右室心尖部起搏", "通过室间隔将导线旋入左室间隔内膜下，起搏左束支区域", "只能用于 CRT 患者", "导线置于冠状窦"], correct: 1, explanation: "LBBAP 是生理性起搏新技术：导线通过右室间隔面旋入左室间隔内膜下区域，直接夺获左束支或其分支。优势：QRS 窄（类生理传导）、LVEF 保留优于 RVP。可用于起搏适应证伴 LVEF 减低或预计高起搏比例者。", category: "综合" },
  { id: "z14", question: "关于 CRT（心脏再同步化治疗）的适应证，以下哪项符合 I 类推荐？", options: ["LVEF ≤ 35% + LBBB（QRS ≥ 150ms）+ NYHA II-IV 级窦性心律", "任何宽 QRS 患者", "LVEF 50% 的患者", "RBBB 患者"], correct: 0, explanation: "CRT 最确定的适应证：LVEF ≤ 35% + LBBB + QRS ≥ 150ms + NYHA II-IV（优化药物治疗后）→ I 类推荐。QRS 130-149ms 或非 LBBB（RBBB/非特异性 IVCD）获益较弱（IIa/IIb 类）。窦性心律患者获益最大。", category: "综合" },
  { id: "z15", question: "心房食道调搏（TEAP）主要用于以下哪项目的？", options: ["室速的终止", "SVT 的诱发和初步鉴别诊断", "永久性起搏器植入", "ICD 功能测试"], correct: 1, explanation: "TEAP 是无创电生理检查，经食道电极起搏心房，可用于：① 诱发和终止 SVT（AVNRT、AVRT）② 测量窦房结恢复时间（SNRT）和窦房传导时间（SACT）③ 揭示房室结双径路或旁路。局限性：不能起搏心室。", category: "综合" },
  { id: "z16", question: "关于起搏器介导性心动过速（PMT），以下哪项描述正确？", options: ["由起搏器电池耗竭引起", "室早经房室结逆传心房 → 心房被感知 → 触发心室起搏 → 再逆传 → 形成折返环", "只见于 VVI 模式", "通过增加起搏频率可终止"], correct: 1, explanation: "PMT 常见于 DDD 模式：室早经房室结逆传心房（VA 传导）→ 心房感知 → 触发心室起搏 → 再次逆传 → 形成折返环，起搏频率达上限跟踪频率。处理：延长 PVARP（心室后心房不应期）→ 使逆传 P 波落入不应期不被感知 → 终止 PMT。", category: "综合" },
  { id: "z17", question: "关于心脏电复律的能量选择，以下哪项正确？", options: ["房颤：双相波 50-100J", "房颤：双相波 120-200J", "室颤：双相波 120-200J", "B 和 C 都正确"], correct: 3, explanation: "电复律能量推荐（2015 AHA/ACC）：房颤双相波 120-200J，房扑和 SVT 50-100J，VT 100J（不稳定者 200J），VF 首次 200J（双相波）后逐级递增至 360J。注意：使用双相波除颤器时能量可低于单相波。", category: "综合" },
  { id: "z18", question: "关于 SCN5A 基因突变，以下哪项心律失常与其相关？", options: ["仅 Brugada 综合征", "仅 LQT3", "Brugada 综合征、LQT3、Lenègre 病（进行性心脏传导疾病）等多种表型", "仅 CPVT"], correct: 2, explanation: "SCN5A（心脏钠通道 Nav1.5）突变导致功能丧失（loss-of-function）→ Brugada 综合征或进展性心脏传导疾病（Lenègre 病）；功能获得（gain-of-function）→ LQT3。同一突变可有重叠表型（overlap syndrome），是多效性突变的经典例子。", category: "综合" },
  { id: "z19", question: "关于心房颤动触发灶最常见的解剖位置是？", options: ["冠状窦口", "上腔静脉", "肺静脉（特别是上肺静脉）", "Marshall 韧带"], correct: 2, explanation: "Haissaguerre 等（1998）首次证实肺静脉内触发灶是房颤的主要来源。上肺静脉比下肺静脉更常触发房颤（可能因心肌袖延伸更长、纤维排列更复杂）。其他触发灶：上腔静脉、冠状窦、Marshall 韧带、界嵴、左心耳。", category: "综合" },
  { id: "z20", question: "心脏电生理检查中，以下哪种药物可用于诱发隐匿性旁路的逆传？", options: ["腺苷（抑制房室结，暴露旁路逆传）", "维拉帕米", "阿托品", "胺碘酮"], correct: 0, explanation: "腺苷抑制房室结传导，在心室起搏时可更清晰地显示旁路逆传（消除房室结逆传的干扰）。异丙肾也可通过增加交感张力来促进旁路传导，帮助诱发 AVRT。", category: "综合" },
  { id: "z21", question: "以下哪项不是心脏植入式电子设备（CIED）感染的典型表现？", options: ["囊袋红肿热痛/破溃/流脓", "不明原因发热 + 血培养阳性", "导线赘生物（超声证实）", "起搏阈值升高（这是导线老化的正常现象）"], correct: 3, explanation: "起搏阈值升高可能是导线-组织界面纤维化、药物影响或心肌病变等，不一定提示感染。CIED 感染的典型表现：囊袋局部感染征象（红肿热痛破溃流脓）+ 全身感染征象（发热、寒战、血培养阳性）+ 超声/CT 发现导线/瓣膜赘生物。确诊感染通常需完全取出装置和导线。", category: "综合" },
  { id: "z22", question: "关于 Vaughan Williams 抗心律失常药物分类，III 类药物的主要机制是？", options: ["钠通道阻滞", "β 受体阻滞", "钾通道阻滞（延长复极和不应期）", "钙通道阻滞"], correct: 2, explanation: "III 类药物（胺碘酮、索他洛尔、多非利特、伊布利特）主要通过阻断钾通道（主要是 IKr）延长动作电位时程和不应期。胺碘酮是多通道药物（I+II+III+IV 类效应）。伊布利特主要阻断 IKr 并激活慢钠电流。", category: "综合" },
  { id: "z23", question: "关于心脏移植后心律失常，以下哪项是术后远期最常见的持续性心律失常？", options: ["房颤/房扑", "室速", "高度房室传导阻滞", "交界性心动过速"], correct: 0, explanation: "心脏移植远期心律失常：房颤/房扑最常见（发生率 10-30%），与排斥反应、移植心脏血管病变（CAV）、心房吻合口瘢痕有关。窦房结功能障碍也常见（供心缺血时间、手术损伤）。显著的室性心律失常应评估 CAV 和排斥。", category: "综合" },
  { id: "z24", question: "关于全身麻醉对电生理检查的影响，以下哪项正确？", options: ["麻醉对心律失常诱发无任何影响", "异丙酚和吸入麻醉药可能抑制心律失常诱发", "麻醉可增强房室结传导", "全身麻醉禁用异丙肾"], correct: 1, explanation: "全身麻醉（特别是异丙酚和吸入麻醉药）可抑制心律失常的诱发——特别是 SVT、特发性 VT。因此电生理检查和消融通常在深度镇静或清醒状态下进行。如心律失常不能诱发，可减浅麻醉或加用异丙肾。", category: "综合" },
  { id: "z25", question: "心脏电生理检查中使用肝素的 ACT 监测目标通常为？", options: ["100-150 秒", "200-250 秒", "300-350 秒（左房操作如 AF 消融时）", "> 500 秒"], correct: 2, explanation: "ACT 目标：① 左房操作（房颤消融、左侧旁路消融）→ 300-350 秒 ② 右心操作（AVNRT 慢径消融、CTI 消融）→ 250-300 秒 ③ 室性心律失常消融（涉及左室）→ 250-350 秒。首剂肝素后每 20-30 分钟监测并追加。", category: "综合" },
];

export default QUESTIONS;

